### ISSUE TITLE
add defer.close()

### ISSUE THREAD

**Issue by ravik-karn-tw** [chakradeb/frnd#5]
https://github.com/chakradeb/frnd/blob/22faff1774089af2e8dcca6ac9f34ea6c7dfc08a/server/db/database.go#L27

**Comment by chakradeb** [comment]
Implemented in commit [https://github.com/chakradeb/frnd/commit/55963e6676306af4ea246b03ec5fcc31d28b059c](https://github.com/chakradeb/frnd/commit/55963e6676306af4ea246b03ec5fcc31d28b059c)
